
# PurePerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: 1.4.2
api: [3.0.0]
load: POSTWORLD
author: "64FF00 & ProjectInfinity"
website: https://github.com/PurePlugins/PurePerms
permissions:
  pperms:
    description: "PurePerms por 64FF00! (Twitter: @64FF00)"
    children:
      pperms.command:
        description: "Permite que você use todos os comando do PurePerms."
        children:
          pperms.command.addgroup:
            description: "Adiciona um novo grupo para a lista de grupos."
          pperms.command.addparent:
            description: "Adiciona um grupo à lista de herança de outro grupo."	
          pperms.command.defgroup:
            description: "Permite que você defina um grupo padrão manualmente."
          pperms.command.fperms:
            description: "Encontrar permissões de um puglin em especifico."
          pperms.command.groups:
            description: "Mostra a lista de todos os grupos."
          pperms.command.listgperms:
            description: "Mostra todas as permissões de um grupo."
          pperms.command.listuperms:
            description: "Mostra todas as permissões de um usuário."
          pperms.command.ppinfo:
            default: true
            description: "Mostra informações sobre PurePerms."
          pperms.command.ppreload:
            description: "Recarrega todas as configurações do PurePerms."
          pperms.command.rmgroup:
            description: "Remove um grupo da lista de grupos."
          pperms.command.rmparent:
            description: "Remove um grupo da lista de herança de outro grupo."		
          pperms.command.setgperm:
            description: "Adiciona uma permissão à um grupo."
          pperms.command.setgroup:
            description: "Define um grupo para um usuário"
          pperms.command.setuperm:
            description: "Adiciona uma permissão a um usuário."
          pperms.command.unsetgperm:
            description: "Remove uma permissão de um grupo."
          pperms.command.unsetuperm:
            description: "Remove uma permissão de um usuário."
          pperms.command.usrinfo:
            description: "Mostra informações de um usuário."
      pperms.noeul:
        description: "Permite que você acesse todos os recursos relacionados ao 'Noeul'."
        children:
          pperms.noeul.ppsudo:
            description: "Permite que você use o comando Noeul 'ppsudo'."
